#!/bin/bash

if [[ "$#" -ne 2 ]]; then
    printf "Usage: %s INPUT_FILE OUTPUT_FILE\n\n" $(basename "$0")
    printf "Writes a blurred version of INPUT_FILE to OUTPUT_FILE.\n"
    printf "Requires ImageMagick.\n"
    exit 1
fi

convert -gaussian-blur 75x25 -brightness-contrast -10 "$1" "$2"
