#!/bin/bash -x

if [[ "$#" -ne 1 ]]; then
    printf "Usage: %s INPUT_FILE\n\n" $(basename "$0")

    echo "Blurs the given image, and writes compressed versions of the blurred and original image to the images directory. Requires ImageMagick and Guetzli." | fmt

    exit 1
fi

temp=$(mktemp)
filename=$(basename "$1")
script_dir=$(dirname "$0")
target_dir="$script_dir/images"

# Generate blurred, compressed image
./blur-img "$1" "$temp"
guetzli "$temp" "$target_dir/blurred/$filename"

# Generate compressed image
guetzli "$1" "$target_dir/$filename"
