#!/bin/bash

if [[ "$#" -eq 0 ]]; then
    printf "Usage: %s INPUT_FILE [...]\n\n" $(basename "$0")

    echo "Processes all given image files in parallel"

    exit 1
fi

echo ${@:1} | xargs --verbose -P 0 -n 1 ./process-img
